## YAML Template.
---
spring:
  profiles: docker
  kafka:
    template:
      default-topic: library-events
    consumer:
      bootstrap-servers: kafka:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
    producer:
      bootstrap-servers:
        -   kafka:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      host: mongodb
      port: 27017
      authentication-database: admin
      username: root
      password: admin
      database: test