## YAML Template.
---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/AbstractVersion/micro-env-config.git
#          If the repo is private fill git cridential here
#          username: username/e-mail
#          password: password
  application:
    name: config-server
    
#managment:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh
    
    
# eureka:
#   client:
#     healthcheck:
#       enabled: true
#     serviceUrl:
#       defaultZone: http://discovery-service:8761/eureka/
#     instance:
#       preferIpAddress: true
