## YAML Template.
---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AbstractVersion/micro-env-config.git
#          If the repo is private fill git cridential here
#          username: username/e-mail
#          password: password
  application:
    name: config-server
    
#    
#eureka:
#    instance:
#        hostname: discovery-service
#    client:
#        service-url:
#            defaultZone: http://discovery-service:8761/eureka/
#        register-with-eureka: true