version: '3.7'
networks:
    micro-nework-backend:
      external: true
volumes:
  mysql.vol:
    driver: nfs
    driver_opts:
      share: 192.168.2.4:/mysql
      # https://sysadmins.co.za/docker-swarm-persistent-storage-with-nfs/

services:

  generalRDBMS:
    # container_name: generalRDBMS
    image: mariadb:latest
    volumes:
     - mysql.vol:/var/lib/mysql
    networks:
      - micro-nework-backend
    # restart: on-failure 
    deploy:
        placement:
            constraints:
              - "node.role==manager"
      #Number of replicas
        replicas: 1
      # Configure stack update
        restart_policy:
          condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sessionDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root


    


