version: "3.7"
# Cloud Config Service
networks:
  beats-network:
    driver: bridge

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.2.0
    networks: 
      - beats-network
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
      - ./data:/usr/share/filebeat/data:rw                        # Persistence data
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure
